### ISSUE TITLE
WHERE IS THE SOURCE CODE

### ISSUE THREAD

**Issue by AoifeHughes** [remarkableapp/Remarkable-Linux#26]
I WANNA FIX THE APP BUT CANNOT FIND SOURCE CODE

**Comment by krikmo** [comment]
I am not the creator. You can easily unpack the installers and get the source code. But I understand the frustration. 

Take a look at [this](https://github.com/krikmo/Remarkable) repository, there you should find everything that you need. I will probably not accept Python-related pulls since a) I still don't know enough of Python and b) I don't want to make a project that I can't maintain.

@remarkableapp says that he is re-writing the software but that doesn't mean you can't release your changed version.

**Comment by JPvRiel** [comment]
Look here: https://github.com/jamiemcg/Remarkable/
