### ISSUE TITLE
image of relative path

### ISSUE THREAD

**Issue by changuoqiang** [remarkableapp/Remarkable-Linux#5]
I find the image link like ![foo](foo.jpg) not work properly, the image is from local,not from network, if provide the full absolute path of image, it works, like this, ![foo](/path/to/foo.jpg). but relative path does not work.

**Comment by remarkableapp** [comment]
Currently only absolute paths are implemented.
Relative paths are not supported.

**Comment by jbruni** [comment]
This is an important feature. I'm writing documentation in a repository. I just want to show an image in the very same folder... but it doesn't work, except if I inform the full local path to the image, which will only work in my machine...

**Comment by cyberang3l** [comment]
In order to support relative paths all you need to do is to change the following line in the function update_live_preview from:

`self.live_preview.load_string(html, "text/html", "utf-8", "file://")`

to:

`self.live_preview.load_string(html, "text/html", "utf-8", "file://{}".format(os.path.abspath(self.name)))`

Of course, you need to `import os` in the beginning of the file `RemarkableWindow.py`

At least, works for me.

**Comment by entron** [comment]
Is it possible to create a pull request? This is really an important feature in my opinion.

**Comment by remarkableapp** [comment]
V1.75 supports relative paths for images
The repository is now [located here](https://github.com/jamiemcg/Remarkable).
